apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: falco
  namespace: flux-system
spec:
  chart:
    spec:
      chart: falco
      version: 1.15.0
      sourceRef:
        kind: HelmRepository
        name: falco-repo
        namespace: flux-system
  interval: 1m
  valuesFrom:
    - kind: ConfigMap
      name: falco-values
