apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: process-exec-monitor
spec:
  kprobes:
  - call: "sys_execve"
    syscall: true
    args:
    - index: 0
      type: "string"
    return: true