apiVersion: cilium.io/v2
kind: TetragonTracepoint
metadata:
  name: trace-exec-detect
  namespace: kube-system
spec:
  events:
    - syscall: execve
      match:
        process:
          name: "bash"
