apiVersion: cilium.io/v2
kind: TetragonTracepoint
metadata:
  name: tracepoint-exec
spec:
  selectors:
    - matchBinaries:
        - operator: In
          values:
            - /bin/bash
            - /bin/sh
            - /usr/bin/cat
            - /usr/bin/curl
            - /usr/bin/wget
