apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: tetragontracepoints.cilium.io
spec:
  group: cilium.io
  names:
    kind: TetragonTracepoint
    listKind: TetragonTracepointList
    plural: tetragontracepoints
    singular: tetragontracepoint
  scope: Cluster
  versions:
    - name: v2
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object